---
name: civilizace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - nodejs=16.13.1
  - pip
  - pip:
    - autopep8==2.0.*
    - mypy==1.9.*
    - pylint==3.1.*

    - boolean.py==4.0.*
    - django==5.0.*
    - django-cors-headers==4.3.*
    - django-enumfield==3.*
    - django-extensions==3.2.*
    - django-ipware==6.0.*
    - djangorestframework==3.14.*
    - djangorestframework-simplejwt==5.3.*
    - flask==3.0.*
    - frozendict==2.4.*
    - gspread==6.0.*
    - pillow==10.2.*
    - pydantic==1.* # Breaking change in 2.*
    - pytest==8.1.*
    - pytest-django==4.8.*
    - python-escpos==3.1.*
    - qrcode==7.4.*
