---
name: civilizace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - nodejs=16.13.1
  - pip
  - pip:
    - mypy
    - autopep8
    - pylint
    - Django==4.0.*
    - djangorestframework==3.13.*
    - djangorestframework-simplejwt==5.1.*
    - gspread==5.*
    - django-extensions==3.1.*
    - django-cors-headers>=3.10.*
    - pytest==7.1.*
    - pytest-django==4.5.*
    - pydantic==1.9.*
    - frozendict==2.3.*
    - types-frozendict
    - django-enumfield==3.0.*
    - psycopg2==2.9.5
    - Pillow==9.1.1
    - qrcode==7.3.1
    - django-ipware==4.0.2
    - Flask==2.1.2
    - python-escpos==2.2.0
