# Generated by Django 3.0.6 on 2020-06-09 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancementModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameDataModel')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.TechModel')),
                ('vyroba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.VyrobaModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnhancementInputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='game.EnhancementModel')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_to_enhancements', to='game.ResourceModel')),
            ],
        ),
    ]
