# Generated by Django 3.0.6 on 2021-05-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishTaskMove',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.action',),
        ),
        migrations.CreateModel(
            name='StartTaskMove',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.action',),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.TechModel'),
        ),
        migrations.AddConstraint(
            model_name='assignedtask',
            constraint=models.UniqueConstraint(fields=('task', 'team'), name='assignedtask_pk'),
        ),
        migrations.AddConstraint(
            model_name='taskmapping',
            constraint=models.UniqueConstraint(fields=('task', 'tech'), name='taskmapping_pk'),
        ),
    ]
