# Generated by Django 3.0.6 on 2021-06-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddWonderMove',
        ),
        migrations.DeleteModel(
            name='AttackMove',
        ),
        migrations.DeleteModel(
            name='MaaraMove',
        ),
        migrations.DeleteModel(
            name='SetBuildingDistanceMove',
        ),
        migrations.DeleteModel(
            name='SetTeamDistanceMove',
        ),
    ]
