# Generated by Django 3.0 on 2019-12-16 10:15

from django.db import migrations, models
import django_enumfield.db.fields
import game.models.action


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Game Word')),
                ('description', models.CharField(max_length=150)),
                ('category', django_enumfield.db.fields.EnumField(enum=game.models.action.KeywordCategory)),
                ('argument1', models.IntegerField(null=True)),
                ('argument2', models.IntegerField(null=True)),
            ],
        ),
    ]
