# Generated by Django 3.0.6 on 2020-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_generationtick'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtick',
            name='forceUpdate',
            field=models.BooleanField(default=False),
        ),
    ]
