# Generated by Django 3.0.6 on 2021-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210519_1122'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignedtask',
            name='assignedtask_pk',
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='assignedAt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='completedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='assignedtask',
            constraint=models.UniqueConstraint(fields=('task', 'team'), name='assignedtask_team-task'),
        ),
        migrations.AddConstraint(
            model_name='assignedtask',
            constraint=models.UniqueConstraint(fields=('tech', 'team'), name='assignedtask_team-tech'),
        ),
    ]
