# Generated by Django 3.0 on 2019-12-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_team_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('view', 'Can view stats for the team'), ('play', 'Can play for the team'))},
        ),
    ]
