# Generated by Django 3.0 on 2019-12-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191212_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('stat_team', 'Can view stats for the team'), ('play_team', 'Can play for the team'))},
        ),
    ]
