name: "Backend: Build & Test"

on: [push, pull_request]

jobs:
  backend_build_test:
    name: "Backend: Build & Test (Python ${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.setup }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        setup: ["native", "conda"]
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ matrix.setup }} == "native"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Set up requirements for backend
        if: ${{ matrix.setup }} == "native"
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r backend/requirements.txt
          python --version

      - name: Set up conda for backend
        if: ${{ matrix.setup }} == "conda"
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: civilizace
          environment-file: conda-env.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          cd backend
          pytest
