name: Update Readme badges

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r backend/requirements.txt

      - name: Get pytest coverage
        id: pytest-cov
        run: |
          cd backend
          pytest --cov-report=term-missing:skip-covered | tee pytest-coverage.txt
          cd ..

      - name: Pytest coverage comment
        id: coverage_comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: backend/pytest-coverage.txt

      - name: Update Readme with Coverage Html
        run: |
          sed -i 's~https://img.shields.io/badge/Backend:_Coverage-[0-9%]*-[a-zA-Z]\+.svg~https://img.shields.io/badge/Backend:_Coverage-'"$(echo ${{ steps.coverage_comment.outputs.coverage }} | sed 's/%/%25/g')"'-${{ steps.coverage_comment.outputs.color }}.svg~g' README.md

      - name: Commit & Push changes to Readme
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update badges in README
          commit_user_email: action@github.com
          add_options: "-u"
